### PR TITLE
Static version plus README

### PR DESCRIPTION
**Pull request by jywarren**
I made a fully-static version index.html so that it can be hosted in demo mode on Github Pages, and also run locally without any server. And added a very very brief README file. 

Great work on this! I attempted an SVG implementation but don't really know how to write a parser :-)

But I have another idea for it! Coming soon.

### CODE REVIEW

**Comment by rmmh** [comment]
thanks for the PR, this looks like a good idea! can you squash this into a single change? (if you don't know how, that's fine)

**Comment by jywarren** [comment]
I think I can use git rebase to squash these, but haven't done it before.

Are you interested in the other pull requests as well? Shall I squash them
too?

**Comment by jywarren** [comment]
Done! and I learned something. :-)

**Comment by jywarren** [comment]
Link fixed.

**Comment by rmmh** [comment]
thanks!

**Pull request merged**
